### ISSUE TITLE
[FT] Improvements to use this plugin for aesthetic reasons. 

### ISSUE THREAD

**Issue by albertoloscerritos** [ALegendsTale/obsidian-color-palette#10]
Hi, first of all great plugin. Thanks for the awesome job.
The other day I came across the the following notion template, and I saw this cute horizontal bar:

![image](https://github.com/ALegendsTale/obsidian-color-palette/assets/16707033/9fefbf3b-5b85-4d21-b8f9-e24ab71b9f88)

I think it could be useful as a line separator (like the --- line) or simply for aesthetic reasons. 
I have been thinking on how to implement this, I am a complete css beginner. However, I figured out a way to achieve this using your plugin. 
I just had to add more columns of colors, reduce the bar height, and add some transparent colors in between the different colors. 

However, there are some options that I think would make the experience better.
1) Option for the bar to do nothing when hovering over the different colors i.e. let the palette be completely unresponsive
![color_p](https://github.com/ALegendsTale/obsidian-color-palette/assets/16707033/14bc1f1f-e41e-4036-aef0-f227c257de13)

2) Having the option to remove the borders at the edges of the bar, so it is an actual rectangle.
![image](https://github.com/ALegendsTale/obsidian-color-palette/assets/16707033/d71f9393-e763-4114-b7c9-979033b762c0)

3) Finally, having the option to access css variables of colors. For example I use the AnuPpuccin theme. It has multiple color variables that change depending on the flavor of the theme you choose. For example, the variable --ctp-peach (an rgb variable) (https://github.com/search?q=repo%3AAnubisNekhet%2FAnuPpuccin%20ctp-peach&type=code) would change depending on the flavor of theme. So, if I hard coded it in a pallet, once I change the theme from light to dark, the color would not be updated. 

Thanks for reading and hopefully you like some of my ideas. Have a great day.

**Comment by ALegendsTale** [comment]
Hello, thank you for the suggestions.

I have [implemented](https://github.com/ALegendsTale/obsidian-color-palette/releases/tag/2.6.0) the first and second ideas as new settings.

As for the third, that might be a little difficult since palettes are generated. The best I can think of right now might be generating random variables per color on each palette. That would result in a lot of random CSS variables though. 

Or maybe variables that are generated based on user set aliases.

Is that what you had in mind?

**Comment by albertoloscerritos** [comment]
Hi. First of all, thank you so much. Just tried the new update and it works great.
Regarding the third point of my original post, what I was suggesting was the ability of manually adding css variables. For example, when I create a css snippet to make a custom callout, I can change the background color in two ways
First 
```
.callout[data-callout="custom"] {
    --callout-icon: lucide-layout-dashboard;
    background-color: rgb(22, 36, 220);
 }
```
In this case, the format of the color: `rgb(22, 36, 220);` is also accepted by you palette plugin i.e. I can manually copy that rgb line, paste it in your palette and it will work:
![image](https://github.com/ALegendsTale/obsidian-color-palette/assets/16707033/6e701688-8c74-4913-b4d3-35a89dd8e5f5)
(third line)

The second way to change the background color of a callout is by using a css variable:
```
.callout[data-callout="custom"] {
    --callout-color: rgb(var(--ctp-sapphire)); 
 }
```

`--ctp-sapphire` is a variable defined in the theme I use. I use those variables a lot in snippets and so on, because those colors change depending on the "flavor" of the theme I use. So `--ctp-sapphire` in light mode is not the same color as `--ctp-sapphire` in dark mode. That is helpful because when creating, for example, custom callouts the color palettes will update automatically. And this is what I can't do with your plugin. If I add that variable `rgb(var(--ctp-sapphire)); ` to one palette it won't detect the color:
![image](https://github.com/ALegendsTale/obsidian-color-palette/assets/16707033/d39aadf6-8546-4006-b01d-643caee43526)
(first line).
I know this may be something very niche, I just tough it would be a cool idea. 

Also, this may be intended behavior, but I noticed that palettes wont detect color in rgb format if there is no spaces between the number i.e. 
`rgb(0,250,250);` this won't work
`rgb(0, 250, 250);` this works

Thanks for the awesome job :)

**Comment by ALegendsTale** [comment]
Thank you for letting me know of the spaces issue. A fix will be coming for it soon.

Aha I understand what you mean now. I did some experimentation before, and I definitely could hack together a system for variables, including checking their validity. I would need a fair amount of time to ensure the validation is correct though.

Therefore, I was thinking of alternative solutions and came up with a simple idea for "overrides". It could be a new setting which lets users override the validation system so that they could use any inputs they want for colors. This would of course include CSS variables, as the colors in palettes are directly input as CSS.

I'd appreciate your thoughts on this as an alternative.

**Comment by albertoloscerritos** [comment]
Hi, I hope you are having a great Monday.
The option for the "overrides" sounds awesome. As you mentioned, that will allow the use of CSS variables :)

**Comment by ALegendsTale** [comment]
The [latest release](https://github.com/ALegendsTale/obsidian-color-palette/releases/tag/2.7.0) includes the new override setting. It can be toggled directly in palette settings or globally. Enjoy :)

**Comment by albertoloscerritos** [comment]
Thank you, it worked perfectly.
![image](https://github.com/ALegendsTale/obsidian-color-palette/assets/16707033/d74a2e3e-3170-470f-9a5d-11820bbca121)
![image](https://github.com/ALegendsTale/obsidian-color-palette/assets/16707033/9016502d-9756-4ea9-9a01-82a979bf7168)
Awesome plugin, thanks for the great work :)
